/**
 * Supabase Configuration
 * 
 * Get these values from: https://app.supabase.com
 * Settings → API → Project URL & anon public key
 * 
 * ⚠️ INSTRUCTIONS:
 * 1. Go to your Supabase project
 * 2. Settings → API
 * 3. Copy Project URL (looks like: https://xxxxx.supabase.co)
 * 4. Copy anon public key (long string)
 * 5. Replace SUPABASE_URL and SUPABASE_ANON_KEY below
 * 
 * This file is safe to expose (anon key is public)
 */

// TODO: Replace these with your Supabase credentials
const SUPABASE_URL = "https://ajijgjwlsnqggjrinqqp.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqaWpnandsc25xZ2dqcmlucXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NTgzMzAsImV4cCI6MjA4NDEzNDMzMH0.PLHiNfcECKpRw80XG1-Qenc4cIebQXCUP0QlUzJSbaY";

// Supabase Client (using CDN - no build tools needed)
let supabase = null;
let supabaseInitialized = false;

/**
 * Initialize Supabase Client
 * Called once when page loads
 */
async function initSupabase() {
  // Prevent multiple initialization
  if (supabaseInitialized) {
    console.log('ℹ️ Supabase already initialized');
    return;
  }

  try {
    // Load Supabase using the standard CDN
    const supabaseUrl = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
    
    // Use dynamic import to load the module
    const supabaseModule = await import(supabaseUrl);
    const { createClient } = supabaseModule;
    
    // Create client
    supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    supabaseInitialized = true;
    
    console.log('✅ Supabase client initialized');
  } catch (error) {
    console.error('❌ Failed to load Supabase:', error);
    console.log('ℹ️ Retrying with alternative method...');
    
    // Fallback: Load via script tag
    loadSupabaseViaScript();
  }
}

function loadSupabaseViaScript() {
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
  script.type = 'module';
  script.onload = () => {
    console.log('✅ Supabase loaded via script tag');
    // Give it a moment to initialize
    setTimeout(() => {
      if (window.supabase && window.supabase.createClient) {
        supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
        supabaseInitialized = true;
        console.log('✅ Supabase client ready');
      }
    }, 500);
  };
  script.onerror = () => {
    console.error('❌ Failed to load Supabase CDN');
  };
  document.head.appendChild(script);
}

// Initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initSupabase);
} else {
  initSupabase();
}

/**
 * Save order to Supabase database
 * Called after user clicks "Order on WhatsApp"
 * 
 * @param {object} orderData - Order details
 * @returns {Promise<object>} - Saved order or error
 */
async function saveOrderToSupabase(orderData) {
  try {
    // Check if Supabase is initialized
    if (!supabase) {
      console.warn('⚠️ Supabase not initialized yet');
      return { success: false, error: 'Supabase not ready' };
    }

    // Validate data
    if (!orderData.customer_name || !orderData.customer_address) {
      return { 
        success: false, 
        error: 'Name and address are required' 
      };
    }

    // Prepare order data for database
    const order = {
      customer_name: orderData.customer_name.trim(),
      customer_address: orderData.customer_address.trim(),
      items: orderData.items, // Will be stored as JSON
      total_amount: orderData.total_amount,
      order_status: 'Pending' // Default status
      // created_at is auto-generated by database
    };

    // Insert into Supabase
    const { data, error } = await supabase
      .from('orders')
      .insert([order])
      .select();

    if (error) {
      console.error('❌ Supabase error:', error);
      return { 
        success: false, 
        error: `Database error: ${error.message}` 
      };
    }

    console.log('✅ Order saved to Supabase:', data);
    return { 
      success: true, 
      data: data[0],
      message: 'Order saved successfully' 
    };

  } catch (err) {
    console.error('❌ Error saving order:', err);
    return { 
      success: false, 
      error: err.message 
    };
  }
}

/**
 * Fetch all orders from Supabase
 * Used in admin panel
 * 
 * @returns {Promise<array>} - Array of orders
 */
async function fetchAllOrders() {
  try {
    if (!supabase) {
      console.error('❌ Supabase not initialized');
      return [];
    }

    // Fetch orders sorted by newest first
    const { data, error } = await supabase
      .from('orders')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('❌ Supabase fetch error:', error);
      return [];
    }

    console.log(`✅ Fetched ${data.length} orders from Supabase`);
    return data || [];

  } catch (err) {
    console.error('❌ Error fetching orders:', err);
    return [];
  }
}

/**
 * Subscribe to real-time order updates
 * Calls callback whenever new order is added
 * 
 * @param {function} callback - Function to call with new order
 * @returns {object} - Unsubscribe function
 */
function subscribeToOrders(callback) {
  if (!supabase) {
    console.error('❌ Supabase not initialized');
    return null;
  }

  const subscription = supabase
    .channel('public:orders')
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: 'orders'
      },
      (payload) => {
        console.log('🔄 New order received (real-time):', payload.new);
        callback(payload.new);
      }
    )
    .subscribe();

  return subscription;
}

/**
 * Update order status
 * Admin can mark orders as "Confirmed", "Preparing", "Ready", etc.
 * 
 * @param {number} orderId - Order ID
 * @param {string} status - New status
 * @returns {Promise<object>} - Updated order or error
 */
async function updateOrderStatus(orderId, status) {
  try {
    if (!supabase) {
      return { success: false, error: 'Supabase not initialized' };
    }

    const { data, error } = await supabase
      .from('orders')
      .update({ order_status: status })
      .eq('id', orderId)
      .select();

    if (error) {
      return { success: false, error: error.message };
    }

    console.log('✅ Order status updated:', data);
    return { success: true, data: data[0] };

  } catch (err) {
    console.error('❌ Error updating order:', err);
    return { success: false, error: err.message };
  }
}

// Initialize Supabase when page loads
document.addEventListener('DOMContentLoaded', () => {
  initSupabase();
});

// Also try to initialize if document is already loaded
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initSupabase);
} else {
  initSupabase();
}
